DEFAULT_MODEL = "gpt-image-2"
DEFAULT_PROVIDER = "packyapi"
DEFAULT_SIZE = "2160x3840"
DEFAULT_QUALITY = "high"
DEFAULT_OUTPUT_FORMAT = "png"
DEFAULT_ASPECT_RATIO = "3:4"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 120
DEFAULT_ENDPOINT = "/v1/images/generations"
DEFAULT_COMPLETION_WINDOW = "24h"
API_ENABLED_ENV = "IMAGE_FACTORY_API_ENABLED"
API_BASE_URL_ENV = "IMAGE_FACTORY_API_BASE_URL"
API_KEY_ENV = "IMAGE_FACTORY_API_KEY"
API_TIMEOUT_ENV = "IMAGE_FACTORY_API_TIMEOUT_SECONDS"

REQUIRED_SCENE_COLUMNS = ("id", "character", "scene", "mood", "shot", "lighting")
